/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_tome_keyword = 2,
  anon_sym_open = 3,
  anon_sym_sealed = 4,
  anon_sym_hidden = 5,
  anon_sym_known = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  sym_silent_keyword = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_rune = 13,
  anon_sym_sigil = 14,
  anon_sym_glyph = 15,
  anon_sym_word = 16,
  anon_sym_mark = 17,
  anon_sym_trace = 18,
  anon_sym_law = 19,
  anon_sym_EQ = 20,
  anon_sym_cast = 21,
  anon_sym_conjure = 22,
  anon_sym_if = 23,
  anon_sym_SEMI = 24,
  anon_sym_EQ_EQ = 25,
  anon_sym_BANG_EQ = 26,
  anon_sym_LT = 27,
  anon_sym_GT = 28,
  anon_sym_LT_EQ = 29,
  anon_sym_GT_EQ = 30,
  anon_sym_PLUS = 31,
  anon_sym_DASH = 32,
  anon_sym_STAR = 33,
  anon_sym_SLASH = 34,
  anon_sym_PERCENT = 35,
  sym_identifier = 36,
  sym_number = 37,
  sym_string = 38,
  sym_source_file = 39,
  sym_tome_declaration = 40,
  sym_visibility_modifier = 41,
  sym_tome_body = 42,
  sym_statement = 43,
  sym_ritual_declaration = 44,
  sym_parameter_list = 45,
  sym_parameter = 46,
  sym_type = 47,
  sym_rune_type = 48,
  sym_law_declaration = 49,
  sym_cast_statement = 50,
  sym_conjure_statement = 51,
  sym_if_statement = 52,
  sym_block = 53,
  sym_expression_statement = 54,
  sym_parenthesized_expression = 55,
  sym_expression = 56,
  sym_call_expression = 57,
  sym_binary_expression = 58,
  sym_operator = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_tome_body_repeat1 = 61,
  aux_sym_parameter_list_repeat1 = 62,
  aux_sym_call_expression_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_tome_keyword] = "tome_keyword",
  [anon_sym_open] = "open",
  [anon_sym_sealed] = "sealed",
  [anon_sym_hidden] = "hidden",
  [anon_sym_known] = "known",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_silent_keyword] = "silent_keyword",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_rune] = "rune",
  [anon_sym_sigil] = "sigil",
  [anon_sym_glyph] = "glyph",
  [anon_sym_word] = "word",
  [anon_sym_mark] = "mark",
  [anon_sym_trace] = "trace",
  [anon_sym_law] = "law",
  [anon_sym_EQ] = "=",
  [anon_sym_cast] = "cast",
  [anon_sym_conjure] = "conjure",
  [anon_sym_if] = "if",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym_tome_declaration] = "tome_declaration",
  [sym_visibility_modifier] = "visibility_modifier",
  [sym_tome_body] = "tome_body",
  [sym_statement] = "statement",
  [sym_ritual_declaration] = "ritual_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_rune_type] = "rune_type",
  [sym_law_declaration] = "law_declaration",
  [sym_cast_statement] = "cast_statement",
  [sym_conjure_statement] = "conjure_statement",
  [sym_if_statement] = "if_statement",
  [sym_block] = "block",
  [sym_expression_statement] = "expression_statement",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_expression] = "expression",
  [sym_call_expression] = "call_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_operator] = "operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tome_body_repeat1] = "tome_body_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_tome_keyword] = sym_tome_keyword,
  [anon_sym_open] = anon_sym_open,
  [anon_sym_sealed] = anon_sym_sealed,
  [anon_sym_hidden] = anon_sym_hidden,
  [anon_sym_known] = anon_sym_known,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_silent_keyword] = sym_silent_keyword,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_rune] = anon_sym_rune,
  [anon_sym_sigil] = anon_sym_sigil,
  [anon_sym_glyph] = anon_sym_glyph,
  [anon_sym_word] = anon_sym_word,
  [anon_sym_mark] = anon_sym_mark,
  [anon_sym_trace] = anon_sym_trace,
  [anon_sym_law] = anon_sym_law,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_cast] = anon_sym_cast,
  [anon_sym_conjure] = anon_sym_conjure,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym_tome_declaration] = sym_tome_declaration,
  [sym_visibility_modifier] = sym_visibility_modifier,
  [sym_tome_body] = sym_tome_body,
  [sym_statement] = sym_statement,
  [sym_ritual_declaration] = sym_ritual_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_rune_type] = sym_rune_type,
  [sym_law_declaration] = sym_law_declaration,
  [sym_cast_statement] = sym_cast_statement,
  [sym_conjure_statement] = sym_conjure_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_block] = sym_block,
  [sym_expression_statement] = sym_expression_statement,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_expression] = sym_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_operator] = sym_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tome_body_repeat1] = aux_sym_tome_body_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tome_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_open] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sealed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hidden] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_known] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_silent_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rune] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sigil] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_glyph] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_word] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mark] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_law] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cast] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_conjure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tome_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_visibility_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_tome_body] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_ritual_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_rune_type] = {
    .visible = true,
    .named = true,
  },
  [sym_law_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_cast_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_conjure_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tome_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_function = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_function] = "function",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 65,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(76);
      ADVANCE_MAP(
        '!', 17,
        '"', 12,
        '#', 78,
        '%', 128,
        '(', 92,
        ')', 94,
        '*', 126,
        '+', 124,
        ',', 93,
        '-', 125,
        '/', 127,
        ';', 117,
        '<', 120,
        '=', 110,
        '>', 121,
      );
      if (lookahead == '\\') SKIP(75);
      if (lookahead == 'c') ADVANCE(19);
      if (lookahead == 'g') ADVANCE(45);
      if (lookahead == 'h') ADVANCE(41);
      if (lookahead == 'i') ADVANCE(38);
      if (lookahead == 'k') ADVANCE(53);
      if (lookahead == 'l') ADVANCE(20);
      if (lookahead == 'm') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(59);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead == 's') ADVANCE(33);
      if (lookahead == 't') ADVANCE(56);
      if (lookahead == 'w') ADVANCE(58);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '}') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(184);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(9);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(9);
      if (lookahead == '\r') SKIP(1);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(11);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(11);
      if (lookahead == '\r') SKIP(3);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(10);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '\r') SKIP(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(13);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(13);
      if (lookahead == '\r') SKIP(7);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '!', 17,
        '"', 12,
        '#', 78,
        '%', 128,
        '(', 92,
        ')', 94,
        '*', 126,
        '+', 124,
        ',', 93,
        '-', 125,
        '/', 127,
        ';', 117,
        '<', 120,
        '=', 18,
        '>', 121,
      );
      if (lookahead == '\\') SKIP(2);
      if (lookahead == 'c') ADVANCE(129);
      if (lookahead == 'h') ADVANCE(150);
      if (lookahead == 'i') ADVANCE(147);
      if (lookahead == 'k') ADVANCE(160);
      if (lookahead == 'l') ADVANCE(130);
      if (lookahead == 'o') ADVANCE(169);
      if (lookahead == 's') ADVANCE(142);
      if (lookahead == '{') ADVANCE(88);
      if (lookahead == '}') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(184);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 10:
      ADVANCE_MAP(
        '!', 17,
        '"', 12,
        '#', 78,
        '%', 128,
        '(', 92,
        ')', 94,
        '*', 126,
        '+', 124,
        ',', 93,
        '-', 125,
        '/', 127,
        '<', 120,
        '=', 18,
        '>', 121,
      );
      if (lookahead == '\\') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(184);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == ')') ADVANCE(94);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '=') ADVANCE(109);
      if (lookahead == '\\') SKIP(4);
      if (lookahead == 'g') ADVANCE(156);
      if (lookahead == 'm') ADVANCE(133);
      if (lookahead == 'r') ADVANCE(179);
      if (lookahead == 's') ADVANCE(152);
      if (lookahead == 't') ADVANCE(173);
      if (lookahead == 'w') ADVANCE(168);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(184);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(186);
      if (lookahead == '\\') ADVANCE(73);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '\\') SKIP(8);
      if (lookahead == 's') ADVANCE(151);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 15:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(77);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == '*') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '=') ADVANCE(119);
      END_STATE();
    case 18:
      if (lookahead == '=') ADVANCE(118);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(64);
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(61);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'd') ADVANCE(101);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(82);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'f') ADVANCE(115);
      END_STATE();
    case 39:
      if (lookahead == 'g') ADVANCE(42);
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 40:
      if (lookahead == 'h') ADVANCE(99);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 43:
      if (lookahead == 'j') ADVANCE(68);
      END_STATE();
    case 44:
      if (lookahead == 'k') ADVANCE(103);
      END_STATE();
    case 45:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(97);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 48:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(86);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'o') ADVANCE(48);
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 57:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 58:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 60:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 62:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 63:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 67:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 68:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 69:
      if (lookahead == 'w') ADVANCE(107);
      END_STATE();
    case 70:
      if (lookahead == 'w') ADVANCE(51);
      END_STATE();
    case 71:
      if (lookahead == 'y') ADVANCE(60);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(185);
      END_STATE();
    case 73:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 74:
      if (eof) ADVANCE(76);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 75:
      if (eof) ADVANCE(76);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_tome_keyword);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_open);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_open);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_sealed);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_sealed);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_hidden);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_hidden);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_known);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_known);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_silent_keyword);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_silent_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_rune);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_rune);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_sigil);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_sigil);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_glyph);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_glyph);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_word);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_mark);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_mark);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_trace);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_trace);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_law);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_law);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(118);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_cast);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_cast);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_conjure);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_conjure);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(122);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(123);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(78);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(175);
      if (lookahead == 'o') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(180);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(171);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead == 'i') ADVANCE(159);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(159);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'j') ADVANCE(178);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(182);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(145);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(167);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(154);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(181);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(155);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(172);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(184);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(185);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 13},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 10},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 10},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 11},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 10},
  [75] = {.lex_state = 10},
  [76] = {.lex_state = 10},
  [77] = {.lex_state = 10},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 10},
  [81] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_tome_keyword] = ACTIONS(1),
    [anon_sym_open] = ACTIONS(1),
    [anon_sym_sealed] = ACTIONS(1),
    [anon_sym_hidden] = ACTIONS(1),
    [anon_sym_known] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_silent_keyword] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_rune] = ACTIONS(1),
    [anon_sym_sigil] = ACTIONS(1),
    [anon_sym_glyph] = ACTIONS(1),
    [anon_sym_word] = ACTIONS(1),
    [anon_sym_mark] = ACTIONS(1),
    [anon_sym_trace] = ACTIONS(1),
    [anon_sym_law] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_cast] = ACTIONS(1),
    [anon_sym_conjure] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(71),
    [sym_tome_declaration] = STATE(34),
    [sym_visibility_modifier] = STATE(79),
    [aux_sym_source_file_repeat1] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_tome_keyword] = ACTIONS(7),
    [anon_sym_open] = ACTIONS(9),
    [anon_sym_sealed] = ACTIONS(9),
    [anon_sym_hidden] = ACTIONS(9),
    [anon_sym_known] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(13), 14,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
  [38] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_operator,
    ACTIONS(17), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(19), 14,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
  [76] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_parameter_list,
    ACTIONS(13), 12,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
    ACTIONS(11), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
  [115] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(13), 14,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
  [150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(25), 14,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
  [185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(29), 14,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
  [220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(33), 14,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
  [255] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      sym_operator,
    ACTIONS(37), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(35), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [297] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 12,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_number,
      sym_string,
    ACTIONS(23), 13,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      sym_identifier,
  [333] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      sym_silent_keyword,
    ACTIONS(53), 1,
      anon_sym_law,
    ACTIONS(55), 1,
      anon_sym_cast,
    ACTIONS(57), 1,
      anon_sym_conjure,
    ACTIONS(59), 1,
      anon_sym_if,
    ACTIONS(61), 1,
      sym_identifier,
    STATE(9), 1,
      sym_expression,
    STATE(53), 1,
      sym_visibility_modifier,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
    STATE(12), 2,
      sym_statement,
      aux_sym_tome_body_repeat1,
    ACTIONS(47), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
    STATE(31), 6,
      sym_ritual_declaration,
      sym_law_declaration,
      sym_cast_statement,
      sym_conjure_statement,
      sym_if_statement,
      sym_expression_statement,
  [390] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_silent_keyword,
    ACTIONS(53), 1,
      anon_sym_law,
    ACTIONS(55), 1,
      anon_sym_cast,
    ACTIONS(57), 1,
      anon_sym_conjure,
    ACTIONS(59), 1,
      anon_sym_if,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_expression,
    STATE(53), 1,
      sym_visibility_modifier,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
    STATE(15), 2,
      sym_statement,
      aux_sym_tome_body_repeat1,
    ACTIONS(47), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
    STATE(31), 6,
      sym_ritual_declaration,
      sym_law_declaration,
      sym_cast_statement,
      sym_conjure_statement,
      sym_if_statement,
      sym_expression_statement,
  [447] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_operator,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(69), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(67), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [486] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_operator,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(73), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(71), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [525] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      sym_silent_keyword,
    ACTIONS(83), 1,
      anon_sym_law,
    ACTIONS(86), 1,
      anon_sym_cast,
    ACTIONS(89), 1,
      anon_sym_conjure,
    ACTIONS(92), 1,
      anon_sym_if,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(9), 1,
      sym_expression,
    STATE(53), 1,
      sym_visibility_modifier,
    ACTIONS(98), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
    STATE(15), 2,
      sym_statement,
      aux_sym_tome_body_repeat1,
    ACTIONS(75), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
    STATE(31), 6,
      sym_ritual_declaration,
      sym_law_declaration,
      sym_cast_statement,
      sym_conjure_statement,
      sym_if_statement,
      sym_expression_statement,
  [582] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_operator,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(103), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(101), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [621] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_silent_keyword,
    ACTIONS(53), 1,
      anon_sym_law,
    ACTIONS(55), 1,
      anon_sym_cast,
    ACTIONS(57), 1,
      anon_sym_conjure,
    ACTIONS(59), 1,
      anon_sym_if,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_expression,
    STATE(53), 1,
      sym_visibility_modifier,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
    STATE(15), 2,
      sym_statement,
      aux_sym_tome_body_repeat1,
    ACTIONS(47), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
    STATE(31), 6,
      sym_ritual_declaration,
      sym_law_declaration,
      sym_cast_statement,
      sym_conjure_statement,
      sym_if_statement,
      sym_expression_statement,
  [678] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym_silent_keyword,
    ACTIONS(53), 1,
      anon_sym_law,
    ACTIONS(55), 1,
      anon_sym_cast,
    ACTIONS(57), 1,
      anon_sym_conjure,
    ACTIONS(59), 1,
      anon_sym_if,
    ACTIONS(61), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_expression,
    STATE(53), 1,
      sym_visibility_modifier,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
    STATE(17), 2,
      sym_statement,
      aux_sym_tome_body_repeat1,
    ACTIONS(47), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
    STATE(31), 6,
      sym_ritual_declaration,
      sym_law_declaration,
      sym_cast_statement,
      sym_conjure_statement,
      sym_if_statement,
      sym_expression_statement,
  [735] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(21), 1,
      sym_expression,
    STATE(49), 1,
      sym_parameter,
    STATE(75), 1,
      sym_type,
    STATE(77), 1,
      sym_rune_type,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
    ACTIONS(111), 6,
      anon_sym_rune,
      anon_sym_sigil,
      anon_sym_glyph,
      anon_sym_word,
      anon_sym_mark,
      anon_sym_trace,
  [773] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      sym_identifier,
    ACTIONS(11), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(13), 10,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [800] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_operator,
    STATE(51), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [831] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_operator,
    ACTIONS(121), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [857] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(123), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(127), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [899] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(131), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [920] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(135), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [941] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_operator,
    ACTIONS(43), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(41), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [966] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(141), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(145), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [1008] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(149), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [1029] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
    ACTIONS(153), 10,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
      sym_silent_keyword,
      anon_sym_law,
      anon_sym_cast,
      anon_sym_conjure,
      anon_sym_if,
      sym_identifier,
  [1050] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(49), 1,
      sym_parameter,
    STATE(75), 1,
      sym_type,
    STATE(77), 1,
      sym_rune_type,
    ACTIONS(111), 6,
      anon_sym_rune,
      anon_sym_sigil,
      anon_sym_glyph,
      anon_sym_word,
      anon_sym_mark,
      anon_sym_trace,
  [1077] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_identifier,
    STATE(60), 1,
      sym_parameter,
    STATE(75), 1,
      sym_type,
    STATE(77), 1,
      sym_rune_type,
    ACTIONS(111), 6,
      anon_sym_rune,
      anon_sym_sigil,
      anon_sym_glyph,
      anon_sym_word,
      anon_sym_mark,
      anon_sym_trace,
  [1101] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_tome_keyword,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(79), 1,
      sym_visibility_modifier,
    STATE(35), 2,
      sym_tome_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(9), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
  [1124] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 1,
      sym_tome_keyword,
    STATE(79), 1,
      sym_visibility_modifier,
    STATE(35), 2,
      sym_tome_declaration,
      aux_sym_source_file_repeat1,
    ACTIONS(168), 4,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
  [1147] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(21), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 6,
      ts_builtin_sym_end,
      sym_tome_keyword,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
  [1180] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(3), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1198] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(16), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 6,
      ts_builtin_sym_end,
      sym_tome_keyword,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
  [1228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 6,
      ts_builtin_sym_end,
      sym_tome_keyword,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
  [1240] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(14), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1258] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(13), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1276] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(27), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1294] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_identifier,
    STATE(22), 1,
      sym_expression,
    ACTIONS(63), 2,
      sym_number,
      sym_string,
    STATE(5), 2,
      sym_call_expression,
      sym_binary_expression,
  [1312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 6,
      ts_builtin_sym_end,
      sym_tome_keyword,
      anon_sym_open,
      anon_sym_sealed,
      anon_sym_hidden,
      anon_sym_known,
  [1324] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_call_expression_repeat1,
  [1337] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 3,
      sym_identifier,
      sym_number,
      sym_string,
  [1346] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_parameter_list_repeat1,
  [1359] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_parameter_list_repeat1,
  [1372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_call_expression_repeat1,
  [1385] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_parameter_list_repeat1,
  [1398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_silent_keyword,
    ACTIONS(203), 1,
      sym_identifier,
  [1408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    STATE(61), 1,
      sym_parameter_list,
  [1418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym_parenthesized_expression,
  [1428] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
    STATE(62), 1,
      sym_parameter_list,
  [1438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_tome_body,
  [1448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_block,
  [1458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_block,
  [1484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
  [1494] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_tome_body,
  [1504] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym_silent_keyword,
      sym_identifier,
  [1522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
  [1529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym_identifier,
  [1536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_tome_keyword,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
  [1550] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
  [1557] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
  [1564] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_EQ,
  [1571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_LBRACE,
  [1578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
  [1585] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_identifier,
  [1592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_identifier,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_LBRACE,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_tome_keyword,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 150,
  [SMALL_STATE(7)] = 185,
  [SMALL_STATE(8)] = 220,
  [SMALL_STATE(9)] = 255,
  [SMALL_STATE(10)] = 297,
  [SMALL_STATE(11)] = 333,
  [SMALL_STATE(12)] = 390,
  [SMALL_STATE(13)] = 447,
  [SMALL_STATE(14)] = 486,
  [SMALL_STATE(15)] = 525,
  [SMALL_STATE(16)] = 582,
  [SMALL_STATE(17)] = 621,
  [SMALL_STATE(18)] = 678,
  [SMALL_STATE(19)] = 735,
  [SMALL_STATE(20)] = 773,
  [SMALL_STATE(21)] = 800,
  [SMALL_STATE(22)] = 831,
  [SMALL_STATE(23)] = 857,
  [SMALL_STATE(24)] = 878,
  [SMALL_STATE(25)] = 899,
  [SMALL_STATE(26)] = 920,
  [SMALL_STATE(27)] = 941,
  [SMALL_STATE(28)] = 966,
  [SMALL_STATE(29)] = 987,
  [SMALL_STATE(30)] = 1008,
  [SMALL_STATE(31)] = 1029,
  [SMALL_STATE(32)] = 1050,
  [SMALL_STATE(33)] = 1077,
  [SMALL_STATE(34)] = 1101,
  [SMALL_STATE(35)] = 1124,
  [SMALL_STATE(36)] = 1147,
  [SMALL_STATE(37)] = 1168,
  [SMALL_STATE(38)] = 1180,
  [SMALL_STATE(39)] = 1198,
  [SMALL_STATE(40)] = 1216,
  [SMALL_STATE(41)] = 1228,
  [SMALL_STATE(42)] = 1240,
  [SMALL_STATE(43)] = 1258,
  [SMALL_STATE(44)] = 1276,
  [SMALL_STATE(45)] = 1294,
  [SMALL_STATE(46)] = 1312,
  [SMALL_STATE(47)] = 1324,
  [SMALL_STATE(48)] = 1337,
  [SMALL_STATE(49)] = 1346,
  [SMALL_STATE(50)] = 1359,
  [SMALL_STATE(51)] = 1372,
  [SMALL_STATE(52)] = 1385,
  [SMALL_STATE(53)] = 1398,
  [SMALL_STATE(54)] = 1408,
  [SMALL_STATE(55)] = 1418,
  [SMALL_STATE(56)] = 1428,
  [SMALL_STATE(57)] = 1438,
  [SMALL_STATE(58)] = 1448,
  [SMALL_STATE(59)] = 1458,
  [SMALL_STATE(60)] = 1466,
  [SMALL_STATE(61)] = 1474,
  [SMALL_STATE(62)] = 1484,
  [SMALL_STATE(63)] = 1494,
  [SMALL_STATE(64)] = 1504,
  [SMALL_STATE(65)] = 1514,
  [SMALL_STATE(66)] = 1522,
  [SMALL_STATE(67)] = 1529,
  [SMALL_STATE(68)] = 1536,
  [SMALL_STATE(69)] = 1543,
  [SMALL_STATE(70)] = 1550,
  [SMALL_STATE(71)] = 1557,
  [SMALL_STATE(72)] = 1564,
  [SMALL_STATE(73)] = 1571,
  [SMALL_STATE(74)] = 1578,
  [SMALL_STATE(75)] = 1585,
  [SMALL_STATE(76)] = 1592,
  [SMALL_STATE(77)] = 1599,
  [SMALL_STATE(78)] = 1606,
  [SMALL_STATE(79)] = 1613,
  [SMALL_STATE(80)] = 1620,
  [SMALL_STATE(81)] = 1627,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 1),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 5, 0, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 5, 0, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cast_statement, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cast_statement, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjure_statement, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjure_statement, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tome_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_law_declaration, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_law_declaration, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ritual_declaration, 5, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ritual_declaration, 5, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ritual_declaration, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ritual_declaration, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ritual_declaration, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ritual_declaration, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tome_body, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tome_body, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tome_declaration, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tome_declaration, 4, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_visibility_modifier, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_visibility_modifier, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [225] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rune_type, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_castmagic(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "castmagic",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 20,
      .patch_version = 9,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
